/**
 * assets.ts — Mapa de assets compartilhado entre LoadingScreen (preload) e GameScene.
 */
export const ASSET_MAP: Record<string, string> = {
  bg:               '/sprites/background/gramado.png',
  'ball-common':    '/sprites/bolas-de-futebol/BolaComum.png',
  'ball-1958':      '/sprites/bolas-de-futebol/Bola1958.png',
  'ball-1962':      '/sprites/bolas-de-futebol/Bola1962.png',
  'ball-1970':      '/sprites/bolas-de-futebol/Bola1970.png',
  'ball-1994':      '/sprites/bolas-de-futebol/Bola1994.png',
  'ball-2002':      '/sprites/bolas-de-futebol/Bola2002.png',
  'gk-idle':          '/sprites/goleiro/GoleiroCentro.png',
  'gk-left-high':     '/sprites/goleiro/GoleiroAltoEsquerda.png',
  'gk-center-high':   '/sprites/goleiro/GoleiroCentroCimaA.png',
  'gk-right-high':    '/sprites/goleiro/GoleiroAltoDireita.png',
  'gk-left-mid':      '/sprites/goleiro/GoleiroMeioEsquerda.png',
  'gk-center-mid':    '/sprites/goleiro/GoleiroCentroMeio.png',
  'gk-right-mid':     '/sprites/goleiro/GoleiroMeioDireita.png',
  'gk-left-low':      '/sprites/goleiro/GoleiroMeioEsquerda.png',
  'gk-center-low':    '/sprites/goleiro/GoleiroCentroMeio.png',
  'gk-right-low':     '/sprites/goleiro/GoleiroMeioDireita.png',
  'gk-left-floor':    '/sprites/goleiro/GoleiroBaixoEsquerdaA.png',
  'gk-center-floor':  '/sprites/goleiro/GoleiroCentroMeio.png',
  'gk-right-floor':   '/sprites/goleiro/GoleiroBaixoDireitaA.png',
  'barrier-1':        '/sprites/jogadores-da-barreira/Barreira1.png',
  'barrier-2':        '/sprites/jogadores-da-barreira/Barreira2.png',
  'barrier-3':        '/sprites/jogadores-da-barreira/Barreira3.png',
  'barrier-4':        '/sprites/jogadores-da-barreira/Barreira4.png',
  'barrier-5':        '/sprites/jogadores-da-barreira/Barreira5.png',
  'chico-champion':   '/sprites/chico/Campeao.png',
  'chico-confident':  '/sprites/chico/Confiante.png',
  'chico-talking':    '/sprites/chico/Falando.png',
  'chico-goal1':      '/sprites/chico/Comemorando1.png',
  'chico-goal2':      '/sprites/chico/Comemorando2.png',
  'chico-miss-a':     '/sprites/chico/ErrouA.png',
  'chico-miss-b': '/sprites/chico/ErrouB.png',
}
