sonar.projectKey=PicPay_ms-igaming-football-game-web
sonar.organization=nxgbiqstumcjehqxdrnhyefpsycaavryialkxzjevbfqjzdzsgilzwwgezkpsswareusxfgyqggwwmccvcohbsvxtegwdvrrldwc
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.*,**/test/**,**/mocks/**,**/GameScene/GameScene.tsx,**/game/sounds.ts,**/game/confetti.ts,**/main.tsx,**/types.ts,**/App.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
